stages:
  - deploy

deploy:
  stage: deploy
  image: calavera/cargo-lambda:latest
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - cd remove_special
    - cargo lambda build --release
    - cd ../standardize_case
    - cargo lambda build --release
    

