stages:
  - remove_special
  - standardize_case
variables:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

remove_special_stage:
  stage: remove_special_stage
  image: rust:latest
  script:
    - rustup default stable
    - apt-get update && apt-get install -y wget unzip xz-utils zip musl-tools
    - wget https://ziglang.org/download/0.9.1/zig-linux-x86_64-0.9.1.tar.xz
    - tar -xf zig-linux-x86_64-0.9.1.tar.xz -C /usr/local
    - export PATH=$PATH:/usr/local/zig-linux-x86_64-0.9.1
    - cargo install cargo-lambda
    - rustup target add x86_64-unknown-linux-musl
    - cd remove_special
    - cargo lambda build --release
    - cargo lambda deploy
  only:
    - main

standardize_casestage:
  stage: standardize_case
  image: rust:latest
  script:
    - rustup default stable
    - apt-get update && apt-get install -y wget unzip xz-utils zip musl-tools
    - wget https://ziglang.org/download/0.9.1/zig-linux-x86_64-0.9.1.tar.xz
    - tar -xf zig-linux-x86_64-0.9.1.tar.xz -C /usr/local
    - export PATH=$PATH:/usr/local/zig-linux-x86_64-0.9.1
    - cargo install cargo-lambda
    - rustup target add x86_64-unknown-linux-musl
    - cd standardize_case
    - cargo lambda build --release
    - cargo lambda deploy
  only:
    - main
