[package]
name = "remove_special"
version = "0.1.0"
edition = "2021"



[dependencies]
lambda_runtime = "0.5.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
regex = "1.5.4"
log = "0.4.14"
simple_logger = "1.16.0"
serde_json = "1.0"
